route1: www.example.com?route=route1;project=<P>
route2: www.example.com?route=route2;project=<P>
route3: www.example.com?route=route3;project=<P>
route4: www.example.com?route=route4;project=<P>
route5: www.example.com?route=route5;project=<P>
route6: www.example.com?route=route6;project=<P>
route7: www.example.com?route=route7;project=<P>
