Buckets: https://console.cloud.google.com/storage/browser?project=<P>
Cloud Service Mesh: https://console.cloud.google.com/net-services/trafficdirector/services/list?project=<P>
Cluster: https://console.cloud.google.com/kubernetes/list/overview?project=<P>
Disks: https://console.cloud.google.com/compute/disks?project=<P>
Dns: https://console.cloud.google.com/net-services/dns/zones?project=<P>
IP Addresses: https://console.cloud.google.com/networking/addresses/list?project=<P>
Logs: https://console.cloud.google.com/logs/query;duration=PT1H?project=<P>
Error logs: https://console.cloud.google.com/logs/query;query=severity%3E%3DERROR;duration=PT1H?project=<P>
Load Balancers: https://console.cloud.google.com/net-services/loadbalancing/list/loadBalancers?project=<P>
Secrets: https://console.cloud.google.com/security/secret-manager?project=<P>
Service Accounts: https://console.cloud.google.com/iam-admin/serviceaccounts?project=<P>
Snapshots: https://console.cloud.google.com/compute/snapshots?project=<P>
VMs: https://console.cloud.google.com/compute/instances?project=<P>
Artifacts: https://console.cloud.google.com/artifacts/browse/<P>?project=<P>
Cloud Armor Rules: https://console.cloud.google.com/net-security/securitypolicies/list?project=<P>
# added by gemini:
Cloud SQL: https://console.cloud.google.com/sql/instances?project=<P>
Cloud Functions: https://console.cloud.google.com/functions/list?project=<P>
Cloud Run: https://console.cloud.google.com/run/services?project=<P>
Cloud Build: https://console.cloud.google.com/cloud-build/builds?project=<P>
Pub/Sub: https://console.cloud.google.com/cloudpubsub/topic/list?project=<P>
Dataflow: https://console.cloud.google.com/dataflow/jobs?project=<P>
BigQuery: https://console.cloud.google.com/bigquery?project=<P>
IAM & Admin: https://console.cloud.google.com/iam-admin/iam?project=<P>
Monitoring: https://console.cloud.google.com/monitoring/dashboards/list?project=<P>
Networking: https://console.cloud.google.com/networking/networks/list?project=<P>
Firewall: https://console.cloud.google.com/networking/firewall/list?project=<P>
KMS: https://console.cloud.google.com/security/kms/list?project=<P>
Workflows: https://console.cloud.google.com/workflows/list?project=<P>
Composer: https://console.cloud.google.com/composer/environments/list?project=<P>
Quotas: https://console.cloud.google.com/iam-admin/quotas?project=<P>
Billing: https://console.cloud.google.com/billing?project=<P>
